const originalBoard = [{ number: 0, hasPiece: false, color: 'white', pieceColor: null, pieceIsKing: false },
    { number: 1, hasPiece: true, color:'black', pieceColor: 'red', pieceIsKing: false },
    { number: 2, hasPiece: false, color: 'white', pieceColor: null, pieceIsKing: false },
    { number: 3, hasPiece: true, color:'black', pieceColor: 'red', pieceIsKing: false },
    { number: 4, hasPiece: false, color: 'white', pieceColor: null, pieceIsKing: false },
    { number: 5, hasPiece: true, color:'black', pieceColor: 'red', pieceIsKing: false },
    { number: 6, hasPiece: false, color: 'white', pieceColor: null, pieceIsKing: false },
    { number: 7, hasPiece: true, color:'black', pieceColor: 'red', pieceIsKing: false },
    { number: 8, hasPiece: true, color:'black', pieceColor: 'red', pieceIsKing: false },
    { number: 9, hasPiece: false, color: 'white', pieceColor: null, pieceIsKing: false },
    { number: 10, hasPiece: true, color:'black', pieceColor: 'red', pieceIsKing: false },
    { number: 11, hasPiece: false, color: 'white', pieceColor: null, pieceIsKing: false },
    { number: 12, hasPiece: true, color:'black', pieceColor: 'red', pieceIsKing: false },
    { number: 13, hasPiece: false, color: 'white', pieceColor: null, pieceIsKing: false },
    { number: 14, hasPiece: true, color:'black', pieceColor: 'red', pieceIsKing: false },
    { number: 15, hasPiece: false, color: 'white', pieceColor: null, pieceIsKing: false },
    { number: 16, hasPiece: false, color: 'white', pieceColor: null, pieceIsKing: false },
    { number: 17, hasPiece: true, color:'black', pieceColor: 'red', pieceIsKing: false },
    { number: 18, hasPiece: false, color: 'white', pieceColor: null, pieceIsKing: false },
    { number: 19, hasPiece: true, color:'black', pieceColor: 'red', pieceIsKing: false },
    { number: 20, hasPiece: false, color: 'white', pieceColor: null, pieceIsKing: false },
    { number: 21, hasPiece: true, color:'black', pieceColor: 'red', pieceIsKing: false },
    { number: 22, hasPiece: false, color: 'white', pieceColor: null, pieceIsKing: false },
    { number: 23, hasPiece: true, color:'black', pieceColor: 'red', pieceIsKing: false },
    { number: 24, hasPiece: false, color:'black', pieceColor: null, pieceIsKing: false },
    { number: 25, hasPiece: false, color: 'white', pieceColor: null, pieceIsKing: false },
    { number: 26, hasPiece: false, color:'black', pieceColor: null, pieceIsKing: false },
    { number: 27, hasPiece: false, color: 'white', pieceColor: null, pieceIsKing: false },
    { number: 28, hasPiece: false, color:'black', pieceColor: null, pieceIsKing: false },
    { number: 29, hasPiece: false, color: 'white', pieceColor: null, pieceIsKing: false },
    { number: 30, hasPiece: false, color:'black', pieceColor: null, pieceIsKing: false },
    { number: 31, hasPiece: false, color: 'white', pieceColor: null, pieceIsKing: false },
    { number: 32, hasPiece: false, color: 'white', pieceColor: null, pieceIsKing: false },
    { number: 33, hasPiece: false, color:'black', pieceColor: null, pieceIsKing: false },
    { number: 34, hasPiece: false, color: 'white', pieceColor: null, pieceIsKing: false },
    { number: 35, hasPiece: false, color:'black', pieceColor: null, pieceIsKing: false },
    { number: 36, hasPiece: false, color: 'white', pieceColor: null, pieceIsKing: false },
    { number: 37, hasPiece: false, color:'black', pieceColor: null, pieceIsKing: false },
    { number: 38, hasPiece: false, color: 'white', pieceColor: null, pieceIsKing: false },
    { number: 39, hasPiece: false, color:'black', pieceColor: null, pieceIsKing: false },
    { number: 40, hasPiece: true, color:'black', pieceColor: 'black', pieceIsKing: false },
    { number: 41, hasPiece: false, color: 'white', pieceColor: null, pieceIsKing: false },
    { number: 42, hasPiece: true, color:'black', pieceColor: 'black', pieceIsKing: false },
    { number: 43, hasPiece: false, color: 'white', pieceColor: null, pieceIsKing: false },
    { number: 44, hasPiece: true, color:'black', pieceColor: 'black', pieceIsKing: false },
    { number: 45, hasPiece: false, color: 'white', pieceColor: null, pieceIsKing: false },
    { number: 46, hasPiece: true, color:'black', pieceColor: 'black', pieceIsKing: false },
    { number: 47, hasPiece: false, color: 'white', pieceColor: null, pieceIsKing: false },
    { number: 48, hasPiece: false, color: 'white', pieceColor: null, pieceIsKing: false },
    { number: 49, hasPiece: true, color:'black', pieceColor: 'black', pieceIsKing: false },
    { number: 50, hasPiece: false, color: 'white', pieceColor: null, pieceIsKing: false },
    { number: 51, hasPiece: true, color:'black', pieceColor: 'black', pieceIsKing: false },
    { number: 52, hasPiece: false, color: 'white', pieceColor: null, pieceIsKing: false },
    { number: 53, hasPiece: true, color:'black', pieceColor: 'black', pieceIsKing: false },
    { number: 54, hasPiece: false, color: 'white', pieceColor: null, pieceIsKing: false },
    { number: 55, hasPiece: true, color:'black', pieceColor: 'black', pieceIsKing: false },
    { number: 56, hasPiece: true, color:'black', pieceColor: 'black', pieceIsKing: false },
    { number: 57, hasPiece: false, color: 'white', pieceColor: null, pieceIsKing: false },
    { number: 58, hasPiece: true, color:'black', pieceColor: 'black', pieceIsKing: false },
    { number: 59, hasPiece: false, color: 'white', pieceColor: null, pieceIsKing: false },
    { number: 60, hasPiece: true, color:'black', pieceColor: 'black', pieceIsKing: false },
    { number: 61, hasPiece: false, color: 'white', pieceColor: null, pieceIsKing: false },
    { number: 62, hasPiece: true, color:'black', pieceColor: 'black', pieceIsKing: false },
    { number: 63, hasPiece: false, color: 'white', pieceColor: null, pieceIsKing: false }];
export default originalBoard
