DROP DATABASE IF EXISTS checkers_db;
CREATE DATABASE checkers_db;
USE checkers_db;
CREATE TABLE IF NOT EXISTS games  (id int(5) AUTO_INCREMENT NOT NULL,
playerOne VARCHAR(45), playerTwo VARCHAR(45), playerOneDisplayName VARCHAR(25), playerTwoDisplayName VARCHAR(25), gameOver BOOLEAN, playerOnesTurn BOOLEAN, board JSON, `history` JSON,winner VARCHAR(45)  , createdAt DATETIME DEFAULT CURRENT_TIMESTAMP, updatedAT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY(id)
);
